### ISSUE TITLE
trm-dnl does not build under python3

### ISSUE THREAD

**Issue by paulkerry1** [trmrsh/trm-dnl#1]
After setting TRM_SOFTWARE and then running "pip3 install .", I get this error...

     Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-afr967yq/setup.py", line 10, in <module>
        if os.environ.has_key('TRM_SOFTWARE'):
    AttributeError: '_Environ' object has no attribute 'has_key'

After changing line 10 in setup.py to
if 'TRM_SOFTWARE' in os.environ:

that subsequently fails with...

  trm/dnl/dnl.cc: In function ‘PyObject* init_dnl()’:
  trm/dnl/dnl.cc:992:46: error: ‘Py_InitModule’ was not declared in this scope
       (void) Py_InitModule("_dnl", DanalMethods);
                                                ^
  trm/dnl/dnl.cc:994:1: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by trmrsh** [comment]
and it never will I'm afraid as I have given up on dnl, so it will work under python2 only. I only leave it on github in case there is someone out there who needs it, but I would remove it from your standard installation setup if I were you.
